document.addEventListener("DOMContentLoaded", () => {
    const searchBtn = document.getElementById("searchBtn");
    const aiRecipeContainer = document.getElementById("aiRecipeCards");
    const carouselInner = document.querySelector("#recipeCarousel .carousel-inner");
    const carouselIndicators = document.querySelector(".carousel-indicators");

    // Function to capitalize first letter
    const capitalize = str => str.charAt(0).toUpperCase() + str.slice(1);

    searchBtn.addEventListener("click", () => {
        const queryInput = document.querySelector(".search-bar input");
        const query = queryInput.value.trim();

        if (!query) {
            alert("Please enter a recipe prompt!");
            return;
        }

        // ---------- Add AI Recipe Card ----------
        const colDiv = document.createElement("div");
        colDiv.className = "col-md-4";

        const cardDiv = document.createElement("div");
        cardDiv.className = "card ai-recipe-card shadow-sm h-100";

        const imageKeyword = query.split(" ")[0]; // use first word as keyword
        const img = document.createElement("img");
        img.src = `https://source.unsplash.com/400x300/?${imageKeyword},food`;
        img.alt = query;
        img.className = "card-img-top";

        const cardBody = document.createElement("div");
        cardBody.className = "card-body";
        cardBody.innerHTML = `
            <h5 class="card-title">${capitalize(query)}</h5>
            <h6>Ingredients:</h6>
            <ul>
                <li>Ingredient 1</li>
                <li>Ingredient 2</li>
                <li>Ingredient 3</li>
            </ul>
            <h6>Instructions:</h6>
            <p>Mix all ingredients and cook to taste. Enjoy your meal!</p>
            <a href="#" class="btn btn-accent mt-2"><i class="fas fa-eye me-1"></i>View Recipe</a>
        `;

        cardDiv.append(img, cardBody);
        colDiv.appendChild(cardDiv);
        aiRecipeContainer.appendChild(colDiv);

        // Fade-in effect
        setTimeout(() => { cardDiv.style.opacity = 1; }, 50);

        // ---------- Add Slide to Carousel ----------
        const carouselItem = document.createElement("div");
        carouselItem.className = "carousel-item active";

        const carouselImg = document.createElement("img");
        carouselImg.src = `https://source.unsplash.com/1200x600/?${imageKeyword},food`;
        carouselImg.alt = query;
        carouselImg.className = "d-block w-100 carousel-img";

        const captionDiv = document.createElement("div");
        captionDiv.className = "carousel-caption d-none d-md-block bg-light bg-opacity-75 rounded p-3";
        captionDiv.innerHTML = `
            <h5>${capitalize(query)}</h5>
            <p>Quick recipe generated by AI based on your prompt.</p>
        `;

        carouselItem.append(carouselImg, captionDiv);

        // Remove "active" from previous slides
        carouselInner.querySelectorAll(".carousel-item").forEach(item => item.classList.remove("active"));

        // Append new active slide
        carouselInner.appendChild(carouselItem);

        // Update carousel indicators
        const indicatorBtn = document.createElement("button");
        indicatorBtn.type = "button";
        indicatorBtn.setAttribute("data-bs-target", "#recipeCarousel");
        indicatorBtn.setAttribute("data-bs-slide-to", carouselInner.children.length - 1);
        indicatorBtn.className = "rounded-circle";
        indicatorBtn.setAttribute("aria-label", `Slide ${carouselInner.children.length}`);
        carouselIndicators.appendChild(indicatorBtn);

        // Clear input
        queryInput.value = "";
    });
});

// ---------- Prompt Editor Toggle ----------
const togglePromptBtn = document.getElementById("togglePrompt");
const promptEditor = document.getElementById("promptEditor");
const closePrompt = document.getElementById("closePrompt");
const applyPrompt = document.getElementById("applyPrompt");
const searchInput = document.querySelector(".search-bar input");

// Default prompt template
let finalPrompt = "";

// Open/Close Editor
togglePromptBtn.addEventListener("click", () => {
    promptEditor.style.display = promptEditor.style.display === "none" ? "block" : "none";

    // Put user input into prompt textbox
    document.getElementById("promptText").value = searchInput.value;
});

closePrompt.addEventListener("click", () => {
    promptEditor.style.display = "none";
});

// Apply Modified Prompt
applyPrompt.addEventListener("click", () => {
    finalPrompt = document.getElementById("promptText").value;
    searchInput.value = finalPrompt; // update main search bar
    promptEditor.style.display = "none";
});

// ---------- Generate AI Recipe ----------
document.getElementById("searchBtn").addEventListener("click", () => {
    let userPrompt = searchInput.value;

    if (!userPrompt.trim()) {
        alert("Please enter ingredients or a recipe idea!");
        return;
    }

    generateRecipeCard(userPrompt);
});

// ---------- Fake AI Generator for Demo ----------
function generateRecipeCard(promptText) {
    const output = `
        <div class="col-md-4">
            <div class="card recipe-card shadow-sm h-100">
                <img src="https://source.unsplash.com/400x300/?${promptText}" class="card-img-top rounded">
                <div class="card-body">
                    <h5 class="card-title">${promptText} Recipe</h5>
                    <p class="card-text">AI generated recipe based on: <strong>${promptText}</strong></p>
                    <a href="#" class="btn btn-accent">View Recipe</a>
                </div>
            </div>
        </div>
    `;

    document.getElementById("aiRecipeCards").innerHTML = output;
}
